/**
 * Named aliases over the generated OpenAPI schema.
 *
 * `schema.d.ts` is machine output regenerated by `make types`; nothing imports
 * from it directly except this file, so a contract change surfaces here as a
 * type error in one place rather than scattered across every component.
 */
import type { components } from './schema'

type S = components['schemas']

export type FarmSummary = S['FarmSummary']
export type DataVersion = S['DataVersionResponse']
export type UserRead = S['UserRead']
export type UserRole = S['UserRole']

export type DashboardKpis = S['DashboardKpisResponse']
export type HerdGrowth = S['HerdGrowthResponse']
export type Distribution = S['DistributionResponse']
export type WeightDistribution = S['WeightDistributionResponse']
export type FeedCostSeries = S['FeedCostSeriesResponse']
export type AlertSummary = S['AlertSummaryResponse']
export type Leaderboard = S['LeaderboardResponse']
export type GrowthSeries = S['GrowthSeriesResponse']

export type Hog = S['HogRead']
export type HogStatus = S['HogStatus']
export type HogSex = S['HogSex']
export type ProductionClass = S['ProductionClass']
export type Alert = S['AlertRead']
export type AlertStatus = S['AlertStatus']
export type AlertType = S['AlertType']
export type FeedRecord = S['FeedRecordRead']
export type FeedRecordCreate = S['FeedRecordCreate']
export type HealthRecord = S['HealthRecordRead']
export type HealthRecordCreate = S['HealthRecordCreate']
export type Vaccination = S['VaccinationRead']
export type VaccinationCreate = S['VaccinationCreate']
export type MortalityEvent = S['MortalityEventRead']
export type MortalityEventCreate = S['MortalityEventCreate']
export type BreedingCycle = S['BreedingCycleRead']
export type BreedingCycleCreate = S['BreedingCycleCreate']
export type BreedingCycleUpdate = S['BreedingCycleUpdate']
export type BreedingStatus = S['BreedingStatus']

/**
 * Every list endpoint answers with this envelope rather than a bare array.
 * The generated types spell it out per element type (`Page_HogRead_`), so this
 * is the one generic form the app actually writes against.
 */
export type Page<T> = {
  items: T[]
  total: number
  limit: number
  offset: number
}
