/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token */
        post: operations["refresh_token_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meta/data-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Data Version
         * @description The farm's change counter — one primary-key lookup, polled every ~20s.
         *
         *     A row is created for every farm by the m4_005 trigger, so the miss below is
         *     a guard for a farm inserted while that trigger was disabled, not an expected
         *     path. Reporting version 0 is right in that case: the client then treats any
         *     later number as a change.
         */
        get: operations["get_data_version_api_v1_meta_data_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read My Farm
         * @description The signed-in user's farm.
         *
         *     `currency_code` and `timezone` are here because the dashboard formats every
         *     money figure and every date against them; without this endpoint the client
         *     would have to hardcode both, which is how the currency ended up hardcoded
         *     in the first place.
         */
        get: operations["read_my_farm_api_v1_farms_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update My Farm
         * @description Rename the farm. Manager-only, and the name is the only editable field.
         *
         *     There is no farm_id in the path: a manager administers exactly one farm, and
         *     accepting an id would be an authorization decision this endpoint does not
         *     need to make.
         */
        patch: operations["update_my_farm_api_v1_farms_me_patch"];
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Users
         * @description Staff on the signed-in user's farm. Manager-only.
         *
         *     Scoped to `manager.farm_id`, not to every user: the roster is farm data like
         *     any other, and a worker has no business enumerating their colleagues'
         *     accounts.
         */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create Staff User */
        post: operations["create_staff_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Staff Role
         * @description Move a colleague between worker and viewer. Manager-only, farm-scoped.
         *
         *     Two guards, both about not being able to lock a farm out of its own
         *     settings. Nothing in this application can promote anyone to manager — not
         *     registration, which always creates a new farm, and not `POST /users`, whose
         *     schema refuses the role. So a manager who could demote themselves, or each
         *     other, would leave the farm with no one able to administer it and no way
         *     back short of editing the database.
         */
        patch: operations["update_staff_role_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/hogs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Hogs */
        get: operations["list_hogs_api_v1_hogs_get"];
        put?: never;
        /** Create Hog */
        post: operations["create_hog_api_v1_hogs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hogs/{hog_id}/growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hog Growth Series */
        get: operations["hog_growth_series_api_v1_hogs__hog_id__growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hogs/{hog_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Hog */
        get: operations["get_hog_api_v1_hogs__hog_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Hog */
        patch: operations["update_hog_api_v1_hogs__hog_id__patch"];
        trace?: never;
    };
    "/api/v1/feed-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feed Records */
        get: operations["list_feed_records_api_v1_feed_records_get"];
        put?: never;
        /** Create Feed Record */
        post: operations["create_feed_record_api_v1_feed_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feed-records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Feed Record */
        get: operations["get_feed_record_api_v1_feed_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Feed Record */
        patch: operations["update_feed_record_api_v1_feed_records__record_id__patch"];
        trace?: never;
    };
    "/api/v1/health-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Health Records */
        get: operations["list_health_records_api_v1_health_records_get"];
        put?: never;
        /** Create Health Record */
        post: operations["create_health_record_api_v1_health_records_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health-records/{record_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health Record */
        get: operations["get_health_record_api_v1_health_records__record_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Health Record */
        patch: operations["update_health_record_api_v1_health_records__record_id__patch"];
        trace?: never;
    };
    "/api/v1/vaccinations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Vaccinations
         * @description Doses given, newest first. `due_before` narrows to the ones falling due.
         */
        get: operations["list_vaccinations_api_v1_vaccinations_get"];
        put?: never;
        /** Create Vaccination */
        post: operations["create_vaccination_api_v1_vaccinations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mortality-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mortality Events */
        get: operations["list_mortality_events_api_v1_mortality_events_get"];
        put?: never;
        /**
         * Create Mortality Event
         * @description Record a death, and move the hog to `deceased` in the same transaction.
         *
         *     The two go together by definition. Leaving the status to a separate PATCH
         *     would let a farm accumulate deaths whose animals still count as live herd,
         *     which is exactly how the mortality rate becomes wrong. Manager-only: this is
         *     the one hog transition that cannot be undone by re-editing a field.
         */
        post: operations["create_mortality_event_api_v1_mortality_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breeding-cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Breeding Cycles */
        get: operations["list_breeding_cycles_api_v1_breeding_cycles_get"];
        put?: never;
        /** Create Breeding Cycle */
        post: operations["create_breeding_cycle_api_v1_breeding_cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/breeding-cycles/{cycle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Breeding Cycle */
        get: operations["get_breeding_cycle_api_v1_breeding_cycles__cycle_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Breeding Cycle */
        patch: operations["update_breeding_cycle_api_v1_breeding_cycles__cycle_id__patch"];
        trace?: never;
    };
    "/api/v1/alert-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alert Rules */
        get: operations["list_alert_rules_api_v1_alert_rules_get"];
        put?: never;
        /** Create Alert Rule */
        post: operations["create_alert_rule_api_v1_alert_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alert-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert Rule */
        get: operations["get_alert_rule_api_v1_alert_rules__rule_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Alert Rule */
        patch: operations["update_alert_rule_api_v1_alert_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        /** Create Alert */
        post: operations["create_alert_api_v1_alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_api_v1_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Alert */
        patch: operations["update_alert_api_v1_alerts__alert_id__patch"];
        trace?: never;
    };
    "/api/v1/dashboard/kpis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Kpis */
        get: operations["get_dashboard_kpis_api_v1_dashboard_kpis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Leaderboard
         * @description Best and worst performers over the window.
         *
         *     This is where `underperformers` moved to from `/kpis`. It was always a
         *     ranking rather than a headline figure, and inlining it meant the KPI payload
         *     carried up to fifty rows that most callers discarded.
         */
        get: operations["get_leaderboard_api_v1_dashboard_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/herd-growth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Herd Growth
         * @description Weight distribution over time — the dashboard's headline chart.
         *
         *     Weekly by default because that is the weigh-in cadence; a daily interval on
         *     weekly data produces a chart that is mostly gaps.
         */
        get: operations["get_herd_growth_api_v1_dashboard_herd_growth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/breed-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Breed Distribution
         * @description Herd composition by breed, with mean weight and mean ADG per breed.
         *
         *     Doubles as the breed facet for the dashboard's filters — the list offered in
         *     the UI is exactly what this returns, so there is no separate facets endpoint
         *     that could fall out of step with the data. That is also why this is the one
         *     panel that takes no `breed` parameter: a facet narrowed to the value already
         *     selected offers one option and no way back.
         */
        get: operations["get_breed_distribution_api_v1_dashboard_breed_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/production-class-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Production Class Distribution */
        get: operations["get_production_class_distribution_api_v1_dashboard_production_class_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/weight-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Weight Distribution
         * @description Histogram of each active hog's latest known weight.
         */
        get: operations["get_weight_distribution_api_v1_dashboard_weight_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/feed-cost-series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Feed Cost Series
         * @description Feed spend per bucket, and what each kilogram of gain cost.
         *
         *     The gain denominator counts only animals weighed in both the bucket and the
         *     one before it, so a sale or a birth between buckets cannot masquerade as
         *     herd growth. A breed filter narrows both sides of that ratio, so the cost
         *     per kilogram stays a like-for-like figure rather than one breed's spend over
         *     the whole herd's gain.
         */
        get: operations["get_feed_cost_series_api_v1_dashboard_feed_cost_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/alert-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Alert Summary
         * @description Counts by status and type plus the newest few — the alerts inbox header.
         *
         *     Not date-filtered: an alert raised outside the dashboard's window and still
         *     open is precisely the one worth surfacing.
         */
        get: operations["get_alert_summary_api_v1_dashboard_alert_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/{export_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Csv */
        get: operations["export_csv_api_v1_exports__export_key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness. Claims only that the process is up, so it cannot lie about the DB.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Ready
         * @description Readiness. 503 unless the database answers and is at the expected migration.
         */
        get: operations["health_ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCreate */
        AlertCreate: {
            /** Hog Id */
            hog_id: number;
            alert_type: components["schemas"]["AlertType"];
            /**
             * Alert Date
             * Format: date
             */
            alert_date: string;
            /** Message */
            message: string;
            /** Alert Rule Id */
            alert_rule_id?: number | null;
        };
        /** AlertRead */
        AlertRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /** Alert Rule Id */
            alert_rule_id: number | null;
            alert_type: components["schemas"]["AlertType"];
            /**
             * Alert Date
             * Format: date
             */
            alert_date: string;
            /** Message */
            message: string;
            status: components["schemas"]["AlertStatus"];
            /** Resolution Notes */
            resolution_notes: string | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AlertRuleCreate */
        AlertRuleCreate: {
            /** Name */
            name: string;
            /** Rule Type */
            rule_type: string;
            /** Config Json */
            config_json?: string | null;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** AlertRuleRead */
        AlertRuleRead: {
            /** Id */
            id: number;
            /** Farm Id */
            farm_id: number;
            /** Name */
            name: string;
            /** Rule Type */
            rule_type: string;
            /** Config Json */
            config_json: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AlertRuleUpdate */
        AlertRuleUpdate: {
            /** Name */
            name?: string | null;
            /** Rule Type */
            rule_type?: string | null;
            /** Config Json */
            config_json?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "open" | "acknowledged" | "resolved";
        /** AlertSummaryResponse */
        AlertSummaryResponse: {
            /** By Status */
            by_status: {
                [key: string]: number;
            };
            /** By Type */
            by_type: {
                [key: string]: number;
            };
            /** Recent */
            recent: components["schemas"]["AlertRead"][];
        };
        /**
         * AlertType
         * @enum {string}
         */
        AlertType: "growth_anomaly" | "vaccination_due" | "breeding_event" | "data_gap";
        /** AlertUpdate */
        AlertUpdate: {
            status?: components["schemas"]["AlertStatus"] | null;
            /** Resolution Notes */
            resolution_notes?: string | null;
        };
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
        };
        /** BreedingCycleCreate */
        BreedingCycleCreate: {
            /** Hog Id */
            hog_id: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** Notes */
            notes?: string | null;
        };
        /** BreedingCycleRead */
        BreedingCycleRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /**
             * Start Date
             * Format: date
             */
            start_date: string;
            /** End Date */
            end_date: string | null;
            status: components["schemas"]["BreedingStatus"];
            /** Notes */
            notes: string | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BreedingCycleUpdate */
        BreedingCycleUpdate: {
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            status?: components["schemas"]["BreedingStatus"] | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * BreedingStatus
         * @enum {string}
         */
        BreedingStatus: "ongoing" | "completed" | "aborted";
        /**
         * DashboardKpisResponse
         * @description The headline figures.
         *
         *     `feed_cost_by_currency` and the mixed-currency nulling are gone: a farm holds
         *     exactly one currency now that feed writes take it from `farm.currency_code`,
         *     so the branch that reported `None` for every cost figure was unreachable by
         *     construction (audit i). `currency_code` is reported once, at the top.
         */
        DashboardKpisResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Breed Filter */
            breed_filter: string | null;
            /** Market Weight Kg */
            market_weight_kg: number;
            /** Currency Code */
            currency_code: string;
            /** Hogs With Growth Measure */
            hogs_with_growth_measure: number;
            /** Avg Daily Gain Kg */
            avg_daily_gain_kg: number | null;
            /** Total Weight Gain Kg */
            total_weight_gain_kg: number;
            /** Health Records Count */
            health_records_count: number;
            /** Feed Records Count */
            feed_records_count: number;
            /** Total Feed Kg */
            total_feed_kg: number;
            /** Total Feed Cost */
            total_feed_cost: number;
            /** Feed Cost Per Kg Gain */
            feed_cost_per_kg_gain: number | null;
            /** Fcr */
            fcr: number | null;
            /** Market Ready Count */
            market_ready_count: number;
            /** Active Hogs Count */
            active_hogs_count: number;
            /** Market Ready Measured Count */
            market_ready_measured_count: number;
            /** Market Ready Pct */
            market_ready_pct: number | null;
            /** Mortality Count */
            mortality_count: number;
            /** Mortality Rate Pct */
            mortality_rate_pct: number | null;
            /** Open Alerts Count */
            open_alerts_count: number;
        };
        /**
         * DataVersionResponse
         * @description The client's cache-invalidation signal.
         *
         *     Polled on an interval; when `version` moves, the dashboard invalidates every
         *     query keyed to the farm. One number rather than per-resource versions,
         *     because the alternative is a poll per chart for a farm whose tables all
         *     change together anyway.
         */
        DataVersionResponse: {
            /** Farm Id */
            farm_id: number;
            /** Version */
            version: number;
            /** Updated At */
            updated_at: string | null;
        };
        /** DistributionResponse */
        DistributionResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Group By */
            group_by: string;
            /** Total Hogs */
            total_hogs: number;
            /** Rows */
            rows: components["schemas"]["DistributionRow"][];
            /** Breed Filter */
            breed_filter?: string | null;
        };
        /** DistributionRow */
        DistributionRow: {
            /** Key */
            key: string;
            /** Hog Count */
            hog_count: number;
            /** Avg Weight Kg */
            avg_weight_kg: number | null;
            /** Avg Adg Kg Per Day */
            avg_adg_kg_per_day: number | null;
        };
        /** FarmSummary */
        FarmSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /** Currency Code */
            currency_code: string;
            /** Hog Count */
            hog_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * FarmUpdate
         * @description The name, and only the name.
         *
         *     Currency and timezone stay server-owned. Feed records store `currency_code`
         *     at write time for historical accuracy, so changing a farm's currency would
         *     leave the money charts summing two units; the timezone is set per deployment
         *     and moving it silently reinterprets what "today" meant for existing records.
         */
        FarmUpdate: {
            /** Name */
            name: string;
        };
        /** FeedCostPoint */
        FeedCostPoint: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Feed Kg */
            feed_kg: number;
            /** Feed Cost */
            feed_cost: number;
            /** Cost Per Kg Gain */
            cost_per_kg_gain: number | null;
        };
        /** FeedCostSeriesResponse */
        FeedCostSeriesResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Interval */
            interval: string;
            /** Currency Code */
            currency_code: string;
            /** Points */
            points: components["schemas"]["FeedCostPoint"][];
            /** Breed Filter */
            breed_filter?: string | null;
        };
        /** FeedRecordCreate */
        FeedRecordCreate: {
            /** Hog Id */
            hog_id: number;
            /** Feed Amount */
            feed_amount: number | string;
            /** Feed Cost */
            feed_cost: number | string;
            /**
             * Record Date
             * Format: date
             */
            record_date: string;
        };
        /** FeedRecordRead */
        FeedRecordRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /** Feed Amount */
            feed_amount: string;
            /** Feed Cost */
            feed_cost: string;
            /** Currency Code */
            currency_code: string;
            /**
             * Record Date
             * Format: date
             */
            record_date: string;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** FeedRecordUpdate */
        FeedRecordUpdate: {
            /** Feed Amount */
            feed_amount?: number | string | null;
            /** Feed Cost */
            feed_cost?: number | string | null;
            /** Record Date */
            record_date?: string | null;
        };
        /** GrowthPoint */
        GrowthPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Weight Kg */
            weight_kg: number;
        };
        /** GrowthSeriesResponse */
        GrowthSeriesResponse: {
            /** Hog Id */
            hog_id: number;
            /** Date From */
            date_from: string | null;
            /** Date To */
            date_to: string | null;
            /** Actual */
            actual: components["schemas"]["GrowthPoint"][];
            /** Forecast */
            forecast?: components["schemas"]["GrowthPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthRecordCreate */
        HealthRecordCreate: {
            /** Hog Id */
            hog_id: number;
            /** Weight */
            weight: number | string;
            /** Temperature */
            temperature?: number | string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Record Date
             * Format: date
             */
            record_date: string;
        };
        /** HealthRecordRead */
        HealthRecordRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /** Weight */
            weight: string;
            /** Temperature */
            temperature: string | null;
            /** Notes */
            notes: string | null;
            /**
             * Record Date
             * Format: date
             */
            record_date: string;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HealthRecordUpdate */
        HealthRecordUpdate: {
            /** Weight */
            weight?: number | string | null;
            /** Temperature */
            temperature?: number | string | null;
            /** Notes */
            notes?: string | null;
            /** Record Date */
            record_date?: string | null;
        };
        /** HerdGrowthPointOut */
        HerdGrowthPointOut: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Hog Count */
            hog_count: number;
            /** Avg Weight Kg */
            avg_weight_kg: number;
            /** Median Weight Kg */
            median_weight_kg: number;
            /** P10 Weight Kg */
            p10_weight_kg: number;
            /** P90 Weight Kg */
            p90_weight_kg: number;
        };
        /** HerdGrowthResponse */
        HerdGrowthResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Breed Filter */
            breed_filter: string | null;
            /** Interval */
            interval: string;
            /** Points */
            points: components["schemas"]["HerdGrowthPointOut"][];
        };
        /** HogCreate */
        HogCreate: {
            /** Tag Number */
            tag_number: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Breed */
            breed: string;
            /** @default female */
            sex: components["schemas"]["HogSex"];
            /** @default piglet */
            production_class: components["schemas"]["ProductionClass"];
            /** Dam Id */
            dam_id?: number | null;
            /** Sire Id */
            sire_id?: number | null;
        };
        /** HogRead */
        HogRead: {
            /** Id */
            id: number;
            /** Farm Id */
            farm_id: number;
            /** Tag Number */
            tag_number: string;
            /**
             * Birth Date
             * Format: date
             */
            birth_date: string;
            /** Breed */
            breed: string;
            sex: components["schemas"]["HogSex"];
            production_class: components["schemas"]["ProductionClass"];
            status: components["schemas"]["HogStatus"];
            /** Dam Id */
            dam_id: number | null;
            /** Sire Id */
            sire_id: number | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * HogSex
         * @enum {string}
         */
        HogSex: "male" | "female";
        /**
         * HogStatus
         * @enum {string}
         */
        HogStatus: "active" | "archived" | "deceased";
        /** HogUpdate */
        HogUpdate: {
            /** Tag Number */
            tag_number?: string | null;
            /** Birth Date */
            birth_date?: string | null;
            /** Breed */
            breed?: string | null;
            status?: components["schemas"]["HogStatus"] | null;
            sex?: components["schemas"]["HogSex"] | null;
            production_class?: components["schemas"]["ProductionClass"] | null;
            /** Dam Id */
            dam_id?: number | null;
            /** Sire Id */
            sire_id?: number | null;
        };
        /** LeaderboardResponse */
        LeaderboardResponse: {
            /**
             * Date From
             * Format: date
             */
            date_from: string;
            /**
             * Date To
             * Format: date
             */
            date_to: string;
            /** Breed Filter */
            breed_filter: string | null;
            /** Metric */
            metric: string;
            /** Direction */
            direction: string;
            /** Rows */
            rows: components["schemas"]["LeaderboardRow"][];
        };
        /** LeaderboardRow */
        LeaderboardRow: {
            /** Hog Id */
            hog_id: number;
            /** Tag Number */
            tag_number: string;
            /** Breed */
            breed: string;
            /** Production Class */
            production_class: string;
            /** Adg Kg Per Day */
            adg_kg_per_day: number;
            /** Weight Gain Kg */
            weight_gain_kg: number;
            /** Days */
            days: number;
            /** Feed Kg */
            feed_kg: number;
            /** Fcr */
            fcr: number | null;
            /** Is Underperformer */
            is_underperformer: boolean;
        };
        /** MortalityEventCreate */
        MortalityEventCreate: {
            /** Hog Id */
            hog_id: number;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Cause */
            cause: string;
            /** Notes */
            notes?: string | null;
        };
        /** MortalityEventRead */
        MortalityEventRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /** Farm Id */
            farm_id: number;
            /**
             * Event Date
             * Format: date
             */
            event_date: string;
            /** Cause */
            cause: string;
            /** Notes */
            notes: string | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** Page[AlertRead] */
        Page_AlertRead_: {
            /** Items */
            items: components["schemas"]["AlertRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[AlertRuleRead] */
        Page_AlertRuleRead_: {
            /** Items */
            items: components["schemas"]["AlertRuleRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[BreedingCycleRead] */
        Page_BreedingCycleRead_: {
            /** Items */
            items: components["schemas"]["BreedingCycleRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[FeedRecordRead] */
        Page_FeedRecordRead_: {
            /** Items */
            items: components["schemas"]["FeedRecordRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[HealthRecordRead] */
        Page_HealthRecordRead_: {
            /** Items */
            items: components["schemas"]["HealthRecordRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[HogRead] */
        Page_HogRead_: {
            /** Items */
            items: components["schemas"]["HogRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[MortalityEventRead] */
        Page_MortalityEventRead_: {
            /** Items */
            items: components["schemas"]["MortalityEventRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[UserRead] */
        Page_UserRead_: {
            /** Items */
            items: components["schemas"]["UserRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /** Page[VaccinationRead] */
        Page_VaccinationRead_: {
            /** Items */
            items: components["schemas"]["VaccinationRead"][];
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
        };
        /**
         * ProductionClass
         * @description Where the animal sits in the production cycle.
         *
         *     Orthogonal to sex — a `female` may be a piglet, a gilt or a sow. Drives
         *     expected growth rate, vaccination schedule, and whether a breeding cycle is
         *     valid for the animal at all.
         * @enum {string}
         */
        ProductionClass: "piglet" | "weaner" | "grower" | "finisher" | "gilt" | "sow" | "boar";
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreateStaff */
        UserCreateStaff: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
        };
        /** UserRead */
        UserRead: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["UserRole"];
            /** Farm Id */
            farm_id: number;
        };
        /** UserRegister */
        UserRegister: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name: string;
            /** Farm Name */
            farm_name: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "manager" | "worker" | "viewer" | "admin";
        /**
         * UserRoleUpdate
         * @description The role, and only the role.
         *
         *     Name, email and password stay with the account holder — a manager who can
         *     silently rewrite a colleague's email owns their sign-in.
         */
        UserRoleUpdate: {
            role: components["schemas"]["UserRole"];
        };
        /** VaccinationCreate */
        VaccinationCreate: {
            /** Hog Id */
            hog_id: number;
            /** Vaccine Name */
            vaccine_name: string;
            /**
             * Dose Date
             * Format: date
             */
            dose_date: string;
            /** Next Due Date */
            next_due_date?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** VaccinationRead */
        VaccinationRead: {
            /** Id */
            id: number;
            /** Hog Id */
            hog_id: number;
            /** Farm Id */
            farm_id: number;
            /** Vaccine Name */
            vaccine_name: string;
            /**
             * Dose Date
             * Format: date
             */
            dose_date: string;
            /** Next Due Date */
            next_due_date: string | null;
            /** Notes */
            notes: string | null;
            /** Created By User Id */
            created_by_user_id: number | null;
            /** Updated By User Id */
            updated_by_user_id: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeightBucketOut */
        WeightBucketOut: {
            /** Lower Kg */
            lower_kg: number;
            /** Upper Kg */
            upper_kg: number;
            /** Hog Count */
            hog_count: number;
        };
        /** WeightDistributionResponse */
        WeightDistributionResponse: {
            /**
             * As Of
             * Format: date
             */
            as_of: string;
            /** Breed Filter */
            breed_filter: string | null;
            /** Bucket Kg */
            bucket_kg: number;
            /** Total Hogs */
            total_hogs: number;
            /** Buckets */
            buckets: components["schemas"]["WeightBucketOut"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_data_version_api_v1_meta_data_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DataVersionResponse"];
                };
            };
        };
    };
    read_my_farm_api_v1_farms_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmSummary"];
                };
            };
        };
    };
    update_my_farm_api_v1_farms_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_UserRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_staff_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateStaff"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    update_staff_role_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRoleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_hogs_api_v1_hogs_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["HogStatus"] | null;
                breed?: string | null;
                production_class?: components["schemas"]["ProductionClass"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HogRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_hog_api_v1_hogs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HogCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hog_growth_series_api_v1_hogs__hog_id__growth_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                hog_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrowthSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hog_api_v1_hogs__hog_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hog_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_hog_api_v1_hogs__hog_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                hog_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HogUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HogRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feed_records_api_v1_feed_records_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FeedRecordRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feed_record_api_v1_feed_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedRecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_record_api_v1_feed_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_feed_record_api_v1_feed_records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_health_records_api_v1_health_records_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_HealthRecordRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_health_record_api_v1_health_records_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthRecordCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_health_record_api_v1_health_records__record_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_health_record_api_v1_health_records__record_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                record_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HealthRecordUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthRecordRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vaccinations_api_v1_vaccinations_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                due_before?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_VaccinationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_vaccination_api_v1_vaccinations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VaccinationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VaccinationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mortality_events_api_v1_mortality_events_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                date_from?: string | null;
                date_to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_MortalityEventRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mortality_event_api_v1_mortality_events_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MortalityEventCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MortalityEventRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_breeding_cycles_api_v1_breeding_cycles_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_BreedingCycleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_breeding_cycle_api_v1_breeding_cycles_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreedingCycleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedingCycleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breeding_cycle_api_v1_breeding_cycles__cycle_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedingCycleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_breeding_cycle_api_v1_breeding_cycles__cycle_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycle_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BreedingCycleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreedingCycleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alert_rules_api_v1_alert_rules_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_rule_api_v1_alert_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_rule_api_v1_alert_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_rule_api_v1_alert_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                hog_id?: number | null;
                status?: components["schemas"]["AlertStatus"] | null;
                alert_type?: components["schemas"]["AlertType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_alert_api_v1_alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_api_v1_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_alert_api_v1_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_kpis_api_v1_dashboard_kpis_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Exact breed filter (optional) */
                breed?: string | null;
                /** @description Target live weight (kg) for market-ready % */
                market_weight_kg?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardKpisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_leaderboard_api_v1_dashboard_leaderboard_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Exact breed filter (optional) */
                breed?: string | null;
                metric?: "adg" | "gain" | "fcr";
                direction?: "top" | "bottom";
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_herd_growth_api_v1_dashboard_herd_growth_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Exact breed filter (optional) */
                breed?: string | null;
                interval?: "day" | "week";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HerdGrowthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breed_distribution_api_v1_dashboard_breed_distribution_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_production_class_distribution_api_v1_dashboard_production_class_distribution_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                /** @description Exact breed filter (optional) */
                breed?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_weight_distribution_api_v1_dashboard_weight_distribution_get: {
        parameters: {
            query?: {
                date_to?: string | null;
                /** @description Exact breed filter (optional) */
                breed?: string | null;
                bucket_kg?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeightDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_feed_cost_series_api_v1_dashboard_feed_cost_series_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                interval?: "day" | "week";
                /** @description Exact breed filter (optional) */
                breed?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedCostSeriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_summary_api_v1_dashboard_alert_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertSummaryResponse"];
                };
            };
        };
    };
    export_csv_api_v1_exports__export_key__get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path: {
                export_key: "hogs" | "users" | "feed_records" | "health_records" | "vaccinations" | "mortality_events" | "breeding_cycles" | "alerts" | "alert_rules";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    };
                };
            };
        };
    };
}
