import type { components } from './schema'

/**
 * The single import boundary onto the generated OpenAPI schema.
 *
 * `schema.d.ts` is machine output regenerated by `make types`; nothing else in
 * the app imports it, so a shape change surfaces here rather than in forty
 * screens. Mirrors `web-dashboard/src/lib/api/types.ts`, re-exporting only what
 * the phone actually uses — no exports, leaderboard, or distribution types.
 *
 * Note the numeric types, which are not a mistake in the generator: Pydantic v2
 * serialises `Decimal` as a JSON string, so `HealthRecordRead.weight` is
 * `string` while `GrowthPoint.weight_kg` (a float) is `number`. Run every read
 * through `toNumber()` from `src/lib/format.ts`.
 */

type Schemas = components['schemas']

export type UserRead = Schemas['UserRead']
export type UserRole = UserRead['role']
export type UserCreateStaff = Schemas['UserCreateStaff']
export type UserRoleUpdate = Schemas['UserRoleUpdate']

export type FarmSummary = Schemas['FarmSummary']
export type DataVersionResponse = Schemas['DataVersionResponse']
export type Token = Schemas['Token']

export type Hog = Schemas['HogRead']
export type HogCreate = Schemas['HogCreate']
export type HogUpdate = Schemas['HogUpdate']
export type HogStatus = Hog['status']
export type HogSex = Hog['sex']
export type ProductionClass = Hog['production_class']
export type HogGrowth = Schemas['GrowthSeriesResponse']
export type GrowthPoint = Schemas['GrowthPoint']

export type HealthRecord = Schemas['HealthRecordRead']
export type HealthRecordCreate = Schemas['HealthRecordCreate']

export type FeedRecord = Schemas['FeedRecordRead']
export type FeedRecordCreate = Schemas['FeedRecordCreate']

export type Vaccination = Schemas['VaccinationRead']
export type VaccinationCreate = Schemas['VaccinationCreate']

export type MortalityEvent = Schemas['MortalityEventRead']
export type MortalityEventCreate = Schemas['MortalityEventCreate']

export type BreedingCycle = Schemas['BreedingCycleRead']
export type BreedingCycleCreate = Schemas['BreedingCycleCreate']
export type BreedingCycleUpdate = Schemas['BreedingCycleUpdate']
export type BreedingStatus = BreedingCycle['status']

export type Alert = Schemas['AlertRead']
export type AlertUpdate = Schemas['AlertUpdate']
export type AlertStatus = Alert['status']
export type AlertType = Alert['alert_type']

export type DashboardKpis = Schemas['DashboardKpisResponse']

/**
 * The list envelope. The generator emits `Page_HogRead_`, `Page_AlertRead_`
 * and so on as separate types; one generic is the same shape and does not have
 * to be looked up per resource.
 */
export type Page<T> = {
  items: T[]
  total: number
  limit: number
  offset: number
}

/** Every enum the UI has to render as chips or pills, in display order. */
export const HOG_SEXES: HogSex[] = ['female', 'male']

export const PRODUCTION_CLASSES: ProductionClass[] = [
  'piglet',
  'weaner',
  'grower',
  'finisher',
  'gilt',
  'sow',
  'boar',
]

export const HOG_STATUSES: HogStatus[] = ['active', 'archived', 'deceased']

export const ALERT_STATUSES: AlertStatus[] = ['open', 'acknowledged', 'resolved']

/** Breeding cycles apply to sows and gilts only — the API rejects the rest. */
export const BREEDING_CLASSES: ProductionClass[] = ['sow', 'gilt']
